config/routes.rb
Rails.application.routes.draw do
  get 'recipes/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'recipes#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
require "open-uri"
require "nokogiri"

class RecipesController < ApplicationController
  def new
    if params[:search] == "" || params[:search] == nil
      if params[:search] == ""
        flash[:alert] = "Empty Field"
      end
    else
      @search = params[:search].downcase
      flash[:success] = "Great move"
      scraper
    end
  end

  def scraper
    html = open("http://www.marmiton.org/recettes/recherche.aspx?aqt=#{@search}").read

    doc = Nokogiri::HTML(html, nil, "utf-8")
    # 2. For the first five results
    @results = []
    doc.search(".recipe-card").first(5).each do |element|
    # 3. Create recipe and store it in results
      name = element.search('.recipe-card__title').text.strip
      duration = element.search('.recipe-card__duration__value').text.strip
      rating = element.search('.recipe-card__rating__value').text.strip
      link = element.search('.recipe-card-link').attribute('href').value
      @results << Recipe.new(name: name, duration: duration, rating: rating, link: link)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RecipesScraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/recipes/new.html.erb
<div class="container-fluid">
    <h1 class="title">Match my Fridge</h1>
    <h2 class="sub-title">Find out the most yummy recipes matching your ingredients</h2>

    <div class="d-flex justify-content-center my-5">
      <div class="col-md-4 col-sm-6 col-xs-12">
        <%= form_tag(recipes_new_path, :method => "get",
            class: 'navbar-form navbar-left') do %>
          <div class="input-group">
            <%= search_field_tag :search, params[:search], placeholder: "My fridge have ...", class: "form-control" %>
            <div class="input-group-btn">
              <%= button_tag "Mix", :class => 'btn btn-success',:name => nil%>
            </div>
          </div>
        <% end %>

        <% if flash[:alert] %>
          <div class="alert alert-danger">
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="d-flex justify-content-center my-5" >
      <div class="col-md-8 col-sm-6 col-xs-12 text-center">
      <% if @search %>
      <ul>
        <% @results.each do |result| %>
          <p><i class="fas fa-utensils"></i> <%= result.name %> | <i class="fas fa-clock"></i> <%= result.duration %> min | <i class="fas fa-star"></i> <%= result.rating %>/5 | <a href="http://www.marmiton.org<%= result.link %>">Start cooking!</a></p>
        <% end %>
      </ul>
      <% end %>
      </div>
    </div>

    <div class="d-flex justify-content-center my-5">
      <p><em>Pssssst : A "Choose your diet" feature is coming</em></p>
    </div>

</div>